Repository nexusformat/definitions, pull requests merged in 2020-01, with the labels that each got.

#698 Use consistent terms in manual when names are flexible.
  .gitignore
  utils/dev_nxdl2rst.py
  utils/nxdl2rst.py
Labels: documentation

#715 certain unit tests had failed
  utils/test_nxdl2rst.py
Labels: bug

#702 Ticket663 use gh pages
  README.md
  base_classes/NXcrystal.nxdl.xml
  impatient-guide/index.rst
  jenkins_build
  legacy_docs/README.md
  manual/source/NeXusIntern.pdf
  manual/source/_templates/google_search.html
  manual/source/community.rst
  manual/source/copyright.rst
  manual/source/datarules.rst
  manual/source/design.rst
  manual/source/examples/NX__template__.nxdl.xml
  manual/source/examples/epics/index.rst
  manual/source/examples/h5py/index.rst
  manual/source/examples/lrmecs/index.rst
  manual/source/faq.rst
  manual/source/history.rst
  manual/source/index.rst
  manual/source/installation.rst
  manual/source/introduction-napi.rst
  manual/source/mailinglist.rst
  manual/source/napi-c.rst
  manual/source/napi-f77.rst
  manual/source/napi-f90.rst
  manual/source/napi-idl.rst
  manual/source/napi-java.rst
  manual/source/napi-python.rst
  manual/source/napi.rst
  manual/source/niac.rst
  manual/source/utilities.rst
  nxdl.xsd
  utils/nxdl_desc2rst.py
Labels: documentation

#723 describe field suffixes reserved by NeXus
  manual/source/datarules.rst
Labels: documentation

#726 cleanup in nxdl.xsd
  nxdlTypes.xsd
Labels: documentation

#734 clarify the nature of application definitions
  manual/source/faq.rst
Labels: high priority

#743 From code camp, clarify NXmx/NXdetector depends_on field.
  applications/NXmx.nxdl.xml
Labels: documentation

#744 From code camp, Make NXmx/NXdata optional.
  applications/NXmx.nxdl.xml
Labels: definitions

#745 From code camp, add note to NXmx that file_name and file_time are recommended
  applications/NXmx.nxdl.xml
Labels: documentation

#751 in release notes TOC, add link to each subsection
  utils/create_release_notes.py
Labels: documentation

#736 cite API contributions
  manual/source/examples/index.rst
  manual/source/utilities.rst
Labels: NIAC has requested, documentation, high priority

#752 NXreflections tidy
  base_classes/NXreflections.nxdl.xml
Labels: definitions
