Repository nexusformat/definitions, pull requests merged in 2020-11, with the labels that each got.

#860 Marks NXspecdata as deprecated.
  contributed_definitions/NXspecdata.nxdl.xml
Labels: task

#671 clarify naming convention
  manual/source/datarules.rst
  nxdl.xsd
Labels: NIAC should review, NIAC vote needed, documentation

#808 reserved prefixes for names
  manual/source/datarules.rst
Labels: NIAC vote needed, documentation, enhancement

#790 add @creator_version
  base_classes/NXroot.nxdl.xml
Labels: NIAC should review, NIAC vote needed, definitions, enhancement

#809 consistent naming of parent_child fields
  .gitignore
  manual/source/datarules.rst
Labels: NIAC vote needed, documentation

#861 NXmx: add version attribute
  applications/NXmx.nxdl.xml
Labels: definitions, enhancement

#819 Symbol tables were added to def's that did not have them
  applications/NXfluo.nxdl.xml
  applications/NXindirecttof.nxdl.xml
  applications/NXiqproc.nxdl.xml
  applications/NXlauetof.nxdl.xml
  applications/NXmonopd.nxdl.xml
  applications/NXmx.nxdl.xml
  applications/NXrefscan.nxdl.xml
  applications/NXreftof.nxdl.xml
  applications/NXsas.nxdl.xml
  applications/NXsastof.nxdl.xml
  applications/NXscan.nxdl.xml
  applications/NXsqom.nxdl.xml
  applications/NXstxm.nxdl.xml
  applications/NXtas.nxdl.xml
  applications/NXtofnpd.nxdl.xml
  applications/NXtofraw.nxdl.xml
  applications/NXtofsingle.nxdl.xml
  applications/NXtomo.nxdl.xml
  applications/NXtomophase.nxdl.xml
  applications/NXtomoproc.nxdl.xml
  applications/NXxas.nxdl.xml
  applications/NXxasproc.nxdl.xml
  applications/NXxbase.nxdl.xml
  applications/NXxeuler.nxdl.xml
  applications/NXxkappa.nxdl.xml
  applications/NXxlaue.nxdl.xml
  applications/NXxnb.nxdl.xml
  applications/NXxrot.nxdl.xml
Labels: documentation

#868 Move CI from travis-ci to Github Actions
  .github/workflows/syntax-checks.yml
  environment.yml
Labels: high priority, task
