Repository nexusformat/definitions, pull requests merged in 2020-12, with the labels that each got.

#866 NXdetector: move start_time & end_time OUT of efficiency group
  base_classes/NXdetector.nxdl.xml
Labels: bug

#872 Add entry_identifier_uuid to NXentry
  base_classes/NXentry.nxdl.xml
Labels: NIAC vote needed, enhancement

#873 Add BLUESKY_ as a reserved prefix
  manual/source/datarules.rst
Labels: NIAC vote needed, documentation, enhancement
