Repository nexusformat/definitions, pull requests merged in 2020-10, with the labels that each got.

#802 clarify hierarchy of different detector group base classes
  applications/NXmx.nxdl.xml
  base_classes/NXdetector_group.nxdl.xml
  base_classes/NXdetector_module.nxdl.xml
Labels: documentation

#784 NXroot. Use NX_DATE_TIME and not NX_CHAR
  base_classes/NXroot.nxdl.xml
Labels: NIAC should review

#817 deprecate 2 fields in NXsample
  base_classes/NXsample.nxdl.xml
Labels: NIAC has requested, high priority

#818 add NXdata/@auxiliary_signals attribute
  base_classes/NXdata.nxdl.xml
Labels: NIAC has requested, high priority

#811 add nexpy/nexusformat python package to utilities page
  manual/source/examples/h5py/writer_1_3.rst
  manual/source/examples/h5py/writer_2_1.rst
  manual/source/utilities.rst
  manual/source/validation.rst
Labels: NIAC has requested, documentation

#806 recommend providing time zone in NX_DATE_TIME
  manual/source/datarules.rst
  nxdlTypes.xsd
Labels: NIAC has requested, documentation

#824 NXmonochromator: deprecate _error fields
  base_classes/NXmonochromator.nxdl.xml
Labels: code camp, definitions

#823 NXlog: use average_value_errors instead average_value_error
  base_classes/NXlog.nxdl.xml
Labels: definitions

#813 @default for every base class except NXdata
  base_classes/NXaperture.nxdl.xml
  base_classes/NXattenuator.nxdl.xml
  base_classes/NXbeam.nxdl.xml
  base_classes/NXbeam_stop.nxdl.xml
  base_classes/NXbending_magnet.nxdl.xml
  base_classes/NXcapillary.nxdl.xml
  base_classes/NXcite.nxdl.xml
  base_classes/NXcollimator.nxdl.xml
  base_classes/NXcrystal.nxdl.xml
  base_classes/NXcylindrical_geometry.nxdl.xml
  base_classes/NXdetector.nxdl.xml
  base_classes/NXdetector_group.nxdl.xml
  base_classes/NXdetector_module.nxdl.xml
  base_classes/NXdisk_chopper.nxdl.xml
  base_classes/NXevent_data.nxdl.xml
  base_classes/NXfermi_chopper.nxdl.xml
  base_classes/NXfilter.nxdl.xml
  base_classes/NXflipper.nxdl.xml
  base_classes/NXfresnel_zone_plate.nxdl.xml
  base_classes/NXgeometry.nxdl.xml
  base_classes/NXgrating.nxdl.xml
  base_classes/NXguide.nxdl.xml
  base_classes/NXinsertion_device.nxdl.xml
  base_classes/NXinstrument.nxdl.xml
  base_classes/NXlog.nxdl.xml
  base_classes/NXmirror.nxdl.xml
  base_classes/NXmoderator.nxdl.xml
  base_classes/NXmonitor.nxdl.xml
  base_classes/NXmonochromator.nxdl.xml
  base_classes/NXnote.nxdl.xml
  base_classes/NXoff_geometry.nxdl.xml
  base_classes/NXorientation.nxdl.xml
  base_classes/NXparameters.nxdl.xml
  base_classes/NXpinhole.nxdl.xml
  base_classes/NXpolarizer.nxdl.xml
  base_classes/NXpositioner.nxdl.xml
  base_classes/NXprocess.nxdl.xml
  base_classes/NXreflections.nxdl.xml
  base_classes/NXsample.nxdl.xml
  base_classes/NXsample_component.nxdl.xml
  base_classes/NXsensor.nxdl.xml
  base_classes/NXshape.nxdl.xml
  base_classes/NXslit.nxdl.xml
  base_classes/NXsource.nxdl.xml
  base_classes/NXtransformations.nxdl.xml
  base_classes/NXtranslation.nxdl.xml
  base_classes/NXuser.nxdl.xml
  base_classes/NXvelocity_selector.nxdl.xml
  base_classes/NXxraylens.nxdl.xml
Labels: NIAC has requested, code camp, high priority

#833 Indicate that CIF is the preferred geometry style now
  manual/source/design.rst
Labels: NIAC has requested, documentation, high priority

#839 NXMX: incident_wavelength_weight ---> incident_wavelength_weights
  applications/NXmx.nxdl.xml
Labels: NIAC has requested, definitions, high priority

#840 Add _mask as a reserved suffix.
  manual/source/datarules.rst
Labels: NIAC has requested, code camp, documentation, enhancement, high priority

#849 clarify in manual about mailing list subscriptions
  manual/source/mailinglist.rst
Labels: documentation

#846 group doc element needs more description
  nxdl.xsd
Labels: code camp, documentation

#799 Added missing required dim fields
  applications/NXarpes.nxdl.xml
Labels: definitions, enhancement

#847 Update URLs to correct destinations
  base_classes/NXaperture.nxdl.xml
  base_classes/NXattenuator.nxdl.xml
  base_classes/NXbeam.nxdl.xml
  base_classes/NXbeam_stop.nxdl.xml
  base_classes/NXbending_magnet.nxdl.xml
  base_classes/NXcapillary.nxdl.xml
  base_classes/NXcite.nxdl.xml
  base_classes/NXcollimator.nxdl.xml
  base_classes/NXcrystal.nxdl.xml
  base_classes/NXcylindrical_geometry.nxdl.xml
  base_classes/NXdata.nxdl.xml
  base_classes/NXdetector.nxdl.xml
  base_classes/NXdetector_group.nxdl.xml
  base_classes/NXdetector_module.nxdl.xml
  base_classes/NXdisk_chopper.nxdl.xml
  base_classes/NXentry.nxdl.xml
  base_classes/NXevent_data.nxdl.xml
  base_classes/NXfermi_chopper.nxdl.xml
  base_classes/NXfilter.nxdl.xml
  base_classes/NXflipper.nxdl.xml
  base_classes/NXfresnel_zone_plate.nxdl.xml
  base_classes/NXgeometry.nxdl.xml
  base_classes/NXgrating.nxdl.xml
  base_classes/NXguide.nxdl.xml
  base_classes/NXinsertion_device.nxdl.xml
  base_classes/NXinstrument.nxdl.xml
  base_classes/NXlog.nxdl.xml
  base_classes/NXmirror.nxdl.xml
  base_classes/NXmoderator.nxdl.xml
  base_classes/NXmonitor.nxdl.xml
  base_classes/NXmonochromator.nxdl.xml
  base_classes/NXnote.nxdl.xml
  base_classes/NXoff_geometry.nxdl.xml
  base_classes/NXorientation.nxdl.xml
  base_classes/NXparameters.nxdl.xml
  base_classes/NXpinhole.nxdl.xml
  base_classes/NXpolarizer.nxdl.xml
  base_classes/NXpositioner.nxdl.xml
  base_classes/NXprocess.nxdl.xml
  base_classes/NXreflections.nxdl.xml
  base_classes/NXroot.nxdl.xml
  base_classes/NXsample.nxdl.xml
  base_classes/NXsample_component.nxdl.xml
  base_classes/NXsensor.nxdl.xml
  base_classes/NXshape.nxdl.xml
  base_classes/NXslit.nxdl.xml
  base_classes/NXsource.nxdl.xml
  base_classes/NXsubentry.nxdl.xml
  base_classes/NXtransformations.nxdl.xml
  base_classes/NXtranslation.nxdl.xml
  base_classes/NXuser.nxdl.xml
  base_classes/NXvelocity_selector.nxdl.xml
  base_classes/NXxraylens.nxdl.xml
  impatient-guide/index.rst
Labels: code camp, documentation

#848 clarify notation of tree structure
  manual/source/design.rst
Labels: code camp, documentation

#834 add 5 interpretation attribute values for color images
  manual/source/design.rst
  nxdl.xsd
Labels: NIAC has requested, definitions, high priority

#843 DOC: note the `target` attribute does not work for external file links
  manual/source/design.rst
Labels: NIAC has requested, documentation, high priority

#845 DOC: clarify target value is a suggestion
  utils/nxdl2rst.py
Labels: code camp, documentation

#853 consistent documentation of group @axes attribute
  contributed_definitions/NXspecdata.nxdl.xml
  impatient-guide/index.rst
  manual/source/datarules.rst
  manual/source/examples/abbreviated-nexus-file.xml.txt
  manual/source/examples/axes-byname.xml.txt
  manual/source/examples/complex-hkl-scan.txt
  manual/source/examples/data-linking.xml.txt
  manual/source/examples/h5py/external_master_structure.txt
  manual/source/examples/h5py/index.rst
  manual/source/examples/h5py/prj_test.nexus_structure.txt
  manual/source/examples/h5py/writer_1_3_structure.txt
  manual/source/examples/h5py/writer_2_1_structure.txt
  manual/source/examples/hierarchy-processed.txt
  manual/source/examples/hierarchy-raw.txt
  manual/source/examples/hierarchy-subentry.txt
  manual/source/examples/nxh5write.c
  manual/source/examples/simplescan.txt
  manual/source/examples/simplescanarea.txt
  manual/source/examples/verysimple.txt
  manual/source/examples/xas.txt
  manual/source/strategies.rst
  nxdl.xsd
Labels: documentation
