Repository nexusformat/definitions, pull requests merged in 2021-03, with the labels that each got.

#884 switch repo default branch from master to main
  CHANGES.rst
  utils/create_release_notes.py
  utils/dev_create_release_notes.py
  utils/nxdl2rst.py
Labels: task

#893 remove and delete such redundant repetition
  nxdlTypes.xsd
Labels: bug

#887 Clarify NXtransformations to fix #885
  base_classes/NXtransformations.nxdl.xml
Labels: code camp

#888 Replace incorrect angle units with radians
  nxdlTypes.xsd
Labels: code camp

#895 Capitalise electric charge units
  nxdlTypes.xsd
Labels: code camp

#904 Fix spelling and whitespaces
  nxdl.xsd
  nxdlTypes.xsd
Labels: code camp

#890 added missing type attributes for the fields variable, qx and qy fields
  applications/NXiqproc.nxdl.xml
  applications/NXsqom.nxdl.xml
Labels: code camp

#898 State in the manual that NX_CHAR is the default field type
  manual/source/nxdl-types.rst
  nxdlTypes.xsd
Labels: code camp
