Repository nexusformat/definitions, pull requests merged in 2022-09, with the labels that each got.

#942 NXdetector: Add virtual_pixel_correction_applied
  applications/NXmx.nxdl.xml
  base_classes/NXdetector.nxdl.xml
Labels: NIAC vote needed

#1189 Note more tools for HDF5 files
  manual/source/utilities.rst
Labels: documentation

#1190 1170 nxxas documentation improvement
  applications/NXxas.nxdl.xml
Labels: NIAC approved

#1035 Flux changes for NXmx
  applications/NXmx.nxdl.xml
Labels: NIAC approved

#1047 NXdata errors on an axis, signal or auxiliary signal
  base_classes/NXdata.nxdl.xml
Labels: NIAC should review

#1195 add closing parenthesis in "suggested target" text
  dev_tools/docs/nxdl.py
Labels: bug, documentation

#1188 NXxpcs: clarify use of entry_identifier, entry_identifier_uuid, and scan_number
  contributed_definitions/NXxpcs.nxdl.xml
Labels: documentation, contributions

#1194 NXsas: review minOccurs and group names
  applications/NXsas.nxdl.xml
Labels: definitions

#1183 Allowing the recommended xml attribute for nexus attributes
  nxdl.xsd
Labels: nxdl-syntax

#1198 update the change history
  CHANGES.rst
Labels: documentation

#1201 Deploy by running CI manually
  .github/workflows/ci.yaml
Labels: task, documentation

#1203 repair broken URL under HDF5 File Tools
  manual/source/utilities.rst
Labels: bug, documentation

#1205 NXxpcs: use a valid units type
  contributed_definitions/NXxpcs.nxdl.xml
Labels: bug
