Repository nexusformat/definitions, pull requests merged in 2022-06, with the labels that each got.

#1036 reserve DECTRIS_ prefix
  manual/source/datarules.rst
Labels: documentation

#1051 Change line endings from DOS to Unix in some text file and scripts for #965
  .gitattributes
  manual/source/FDL
  manual/source/examples/epics/tree_structure.txt
  manual/source/examples/epics/write_nexus_file.py
  manual/source/examples/epics/write_nexus_file2.py
Labels: code camp

#913 removed NX_SPE from the definition fields enumeration list
  applications/NXspe.nxdl.xml
Labels: bug

#1008 change g2 unit type to NX_DIMENSIONLESS
  contributed_definitions/NXxpcs.nxdl.xml
Labels: task

#1069 Fix clean target for #962
  Makefile
Labels: code camp

#1071 Use a make variable to define common python for #1072
  Makefile
  manual/source/Makefile
  manual/source/classes/applications/Makefile
  manual/source/classes/base_classes/Makefile
  manual/source/classes/contributed_definitions/Makefile
Labels: code camp

#1022 improve description of the value of the default attribute
  base_classes/NXdata.nxdl.xml
  base_classes/NXentry.nxdl.xml
  base_classes/NXroot.nxdl.xml
  base_classes/NXsubentry.nxdl.xml
  manual/source/datarules.rst
  manual/source/examples/epics/example.h5
  manual/source/examples/epics/tree_structure.txt
  manual/source/examples/epics/write_nexus_file.py
Labels: telco, documentation

#1080 NX_COUNT was missing from the unit categories
  nxdlTypes.xsd
Labels: code camp

#1009 NXxpcs: add NXprocess group
  contributed_definitions/NXxpcs.nxdl.xml
Labels: task, code camp

#1083 delete NXspecdata contributed definition
  contributed_definitions/NXspecdata.nxdl.xml
Labels: code camp

#994 add image_key to NXdetector
  base_classes/NXdetector.nxdl.xml
Labels: definitions

#1082 fix flux units and improve docs
  applications/NXmx.nxdl.xml
Labels: code camp

#1079 use unbuffered stdout for python in make files
  manual/source/Makefile
  manual/source/classes/applications/Makefile
  manual/source/classes/base_classes/Makefile
  manual/source/classes/contributed_definitions/Makefile
Labels: code camp

#1055 590 nxdetector dimensions
  base_classes/NXdetector.nxdl.xml
Labels: code camp

#1068 NX_COMPLEX - Update nxdlTypes.xsd
  nxdlTypes.xsd
  utils/dev_units2rst.py
  utils/units2rst.py
Labels: enhancement, code camp

#1026 execute CI only for the main branch
  .github/workflows/publish-sphinx.yml
  .github/workflows/syntax-checks.yml
Labels: code camp, tests

#1020 Deprecate incr attribute of dimension type
  base_classes/NXfilter.nxdl.xml
  nxdl.xsd
Labels: code camp

#1094 Clean up unreferenced files for #1092
  manual/source/examples/abbreviated-nexus-file.xml.txt
  manual/source/examples/array-dimensions.xml.txt
  manual/source/examples/array-dimensions1.xml.txt
  manual/source/examples/array-dimensions2.xml.txt
  manual/source/examples/array-dimensions3.xml.txt
  manual/source/examples/data-linking.xml.txt
  manual/source/examples/nxdl-doc-fragment-simple.xml
  manual/source/examples/nxdl-trac6-ex1.xml.txt
  manual/source/examples/nxdl-trac6-ex2.xml.txt
  manual/source/napi-java.rst
Labels: task, code camp

#1074 added more specific guidelines to symbols intro definition
  manual/source/defs_intro.rst
Labels: code camp

#971 ARPES: make numbers number types
  applications/NXarpes.nxdl.xml
Labels: task, code camp

#1085 add NeXus Constructor and nxdl_to_hdf5.py
  manual/source/utilities.rst
Labels: documentation, code camp

#1081 Appdefs cannot force NXentry usage but can advise
  manual/source/applying-nexus.rst
Labels: code camp

#1095 adjust string for examples so they appear on new lines
  utils/units2rst.py
Labels: task, documentation, code camp

#1086 improve the 'dimensions' tag rst rendering
  utils/nxdl2rst.py
Labels: task, documentation, code camp

#1091 Add depends_on and NXtransformations to more base classes
  base_classes/NXaperture.nxdl.xml
  base_classes/NXattenuator.nxdl.xml
  base_classes/NXbeam.nxdl.xml
  base_classes/NXbeam_stop.nxdl.xml
  base_classes/NXbending_magnet.nxdl.xml
  base_classes/NXcapillary.nxdl.xml
  base_classes/NXcollimator.nxdl.xml
  base_classes/NXcrystal.nxdl.xml
  base_classes/NXdetector.nxdl.xml
  base_classes/NXdetector_module.nxdl.xml
  base_classes/NXdisk_chopper.nxdl.xml
  base_classes/NXenvironment.nxdl.xml
  base_classes/NXfermi_chopper.nxdl.xml
  base_classes/NXfilter.nxdl.xml
  base_classes/NXflipper.nxdl.xml
  base_classes/NXfresnel_zone_plate.nxdl.xml
  base_classes/NXgrating.nxdl.xml
  base_classes/NXguide.nxdl.xml
  base_classes/NXinsertion_device.nxdl.xml
  base_classes/NXmirror.nxdl.xml
  base_classes/NXmoderator.nxdl.xml
  base_classes/NXmonitor.nxdl.xml
  base_classes/NXmonochromator.nxdl.xml
  base_classes/NXpinhole.nxdl.xml
  base_classes/NXpolarizer.nxdl.xml
  base_classes/NXpositioner.nxdl.xml
  base_classes/NXsample.nxdl.xml
  base_classes/NXsensor.nxdl.xml
  base_classes/NXslit.nxdl.xml
  base_classes/NXsource.nxdl.xml
  base_classes/NXtransformations.nxdl.xml
  base_classes/NXvelocity_selector.nxdl.xml
  base_classes/NXxraylens.nxdl.xml
  base_classes/aperture/aperture.png
  base_classes/attenuator/attenuator.png
  base_classes/beam_stop/beam_stop.png
  base_classes/collimator/collimator.png
  base_classes/disk_chopper/disk_chopper.png
  base_classes/guide/guide.png
  base_classes/mirror/mirror.png
  base_classes/moderator/moderator.png
  base_classes/monitor/monitor.png
  base_classes/pinhole/pinhole.png
  base_classes/slit/slit.png
  base_classes/source/source.png
Labels: task, code camp

#1097 Fix Makefiles to clean up properly
  manual/Makefile
  manual/source/Makefile
  manual/source/classes/Makefile
  manual/source/classes/applications/Makefile
  manual/source/classes/base_classes/Makefile
  manual/source/classes/contributed_definitions/Makefile
Labels: code camp

#1098 refactor nxdl2rst.py to use Python f-strings
  utils/local_utilities.py
  utils/nxdl2rst.py
Labels: task, code camp

#1102 Fix rank bug + add checks
  utils/nxdl2rst.py
Labels: bug, documentation, code camp

#1106 remove duplicate group from NXpinhole
  base_classes/NXpinhole.nxdl.xml
Labels: bug, documentation, code camp

#927 Add geometry information to NXbeam for #925
  base_classes/NXbeam.nxdl.xml
Labels: enhancement, code camp

#1100 Document NXDL file organisation
  manual/source/img/nxdl-files.png
  manual/source/nxdl-files.rst
  manual/source/nxdl.rst
Labels: code camp

#1114 Table of Hypertext Anchors just needs first column
  utils/nxdl2rst.py
Labels: task, documentation, code camp

#1116 apply black to types2rst & units2rst
  utils/types2rst.py
  utils/units2rst.py
Labels: task, code camp

#1109 nxdlTypes.xsd: unit restrictions should be based on xs:string
  nxdlTypes.xsd
Labels: bug

#1112 Cleanup introduction of links element
  manual/source/design.rst
  manual/source/introduction.rst
Labels: documentation, code camp

#1099 document all the new anchors in one page
  .github/env-workflow.yml
  manual/source/classes/index.rst
  requirements.txt
  utils/dev_nxdl2rst.py
  utils/nxdl2rst.py
Labels: documentation, code camp

#1090 added more specific language for the definition fields required value
  base_classes/NXentry.nxdl.xml
Labels: documentation, code camp

#1119 apply "black" code style to most utils/*py files
  utils/build_preparation.py
  utils/create_release_notes.py
  utils/dev_create_release_notes.py
  utils/local_utilities.py
  utils/nxdl_desc2rst.py
  utils/nxdl_summary.py
  utils/test_nxdl.py
  utils/test_nxdl2rst.py
  utils/test_suite.py
  utils/update_copyright_date.py
Labels: task, code camp

#997 ellipsometry proposal
  contributed_definitions/NXellipsometry.nxdl.xml
Labels: code camp

#998 mpes proposal
  contributed_definitions/NXcalibration.nxdl.xml
  contributed_definitions/NXcollectioncolumn.nxdl.xml
  contributed_definitions/NXdeflector.nxdl.xml
  contributed_definitions/NXdistortion.nxdl.xml
  contributed_definitions/NXelectronanalyser.nxdl.xml
  contributed_definitions/NXenergydispersion.nxdl.xml
  contributed_definitions/NXlens_em.nxdl.xml
  contributed_definitions/NXmanipulator.nxdl.xml
  contributed_definitions/NXmanufacturer.nxdl.xml
  contributed_definitions/NXmpes.nxdl.xml
  contributed_definitions/NXregistration.nxdl.xml
  contributed_definitions/NXspindispersion.nxdl.xml
Labels: code camp

#995 apm proposal
  contributed_definitions/NXaperture_em.nxdl.xml
  contributed_definitions/NXapm.nxdl.xml
  contributed_definitions/NXchamber.nxdl.xml
  contributed_definitions/NXcoordinate_system_set.nxdl.xml
  contributed_definitions/NXion.nxdl.xml
  contributed_definitions/NXlens_em.nxdl.xml
  contributed_definitions/NXpeak.nxdl.xml
  contributed_definitions/NXpulser_apm.nxdl.xml
  contributed_definitions/NXpump.nxdl.xml
  contributed_definitions/NXreflectron.nxdl.xml
  contributed_definitions/NXstage_lab.nxdl.xml
Labels: code camp

#1122 remove pyRestTable requirement
  .github/env-workflow.yml
  requirements.txt
  utils/nxdl2rst.py
Labels: task

#858 Fix up NXBeam symbols and polarization
  applications/NXmx.nxdl.xml
  base_classes/NXbeam.nxdl.xml
Labels: NIAC should review

#1127 DOC v2022.06rc1
  .github/workflows/publish-sphinx.yml
  CHANGES.rst
Labels: documentation

#1134 Rewrite makefile, use in worfklows
  .github/env-workflow.yml
  .github/workflows/publish-sphinx.yml
  .github/workflows/syntax-checks.yml
  Makefile
Labels: documentation, workflows

#1135 add NeXus version metadata to vocabulary file
  utils/nxdl2rst.py
Labels: task, documentation

#1137 fix example nxdl.xml files so they pass the syntax checks
  manual/source/examples/NX__template__.nxdl.xml
  manual/source/examples/NXwoni.nxdl.xml
  manual/source/examples/verysimple.nxdl.xml
Labels: bug

#1136 update gitignore and remove all editor settings from the repo
  .gitignore
  .project
  .pydevproject
  .settings/org.eclipse.core.resources.prefs
Labels: task

#1150 add required CNAME file forthe DNS alias of the manual
  .github/workflows/publish-sphinx.yml
Labels: documentation

#1158 add CNAME to the result of a sphinx HTML build
  .github/workflows/publish-sphinx.yml
Labels: workflows

#1159 create CNAME in build result by sphinx so CI works
  .github/workflows/publish-sphinx.yml
  manual/source/CNAME
  manual/source/conf.py
Labels: workflows

#1156 Define use_application_defaults only once
  utils/nxdl2rst.py
Labels: bug, documentation, code camp

#1161 Fix wrong category for NXsnshisto application definition
  contributed_definitions/NXsnshisto.nxdl.xml
Labels: code camp, contributions

#1163 Listing category is either "base class" or "application definition"
  utils/nxdl2rst.py
Labels: bug, documentation

#1160 Fix wrong category for NXsnsevent application definition
  contributed_definitions/NXsnsevent.nxdl.xml
Labels: code camp, contributions
