Repository nexusformat/definitions, pull requests merged in 2024-10, with the labels that each got.

#1485 UPPERCASE to indicate flexible names
  .gitignore
  CHANGES.rst
  applications/NXcanSAS.nxdl.xml
  base_classes/NXdata.nxdl.xml
  dev_tools/docs/nxdl.py
  dev_tools/utils/nxdl_utils.py
  manual/source/conf.py
  manual/source/datarules.rst
  nxdl.xsd
  requirements.txt
Labels: help wanted, high priority, NIAC approved

#1489 complex units, such as eV/mm
  manual/source/nxdl-types.rst
  nxdl.xsd
  nxdlTypes.xsd
Labels: NIAC approved

#1496 emphasize NXcollection is not validated
  base_classes/NXcollection.nxdl.xml
Labels: documentation

#1497 show how to validate an XML file
  manual/source/examples/epics/index.rst
Labels: documentation

#1418 Fairmat 2024: add attributes to NXroot
  base_classes/NXroot.nxdl.xml
Labels: NIAC approved
