Repository nexusformat/definitions, pull requests merged in 2025-01, with the labels that each got.

#1526 Apply corrections and update EPICS area detector attributes example
  manual/source/examples/epics/attributes-reformatted.xml
  manual/source/examples/epics/attributes.xml
Labels: documentation

#1486 add identifierNAME to NXobject
  base_classes/NXobject.nxdl.xml
  manual/source/datarules.rst
Labels: NIAC approved

#1420 Fairmat 2024: specialized base classes on top of NXprocess
  base_classes/NXdistortion.nxdl.xml
  base_classes/NXprocess.nxdl.xml
  base_classes/NXregistration.nxdl.xml
Labels: enhancement, NIAC should review, NIAC approved
